Fix removing the deleting flag
When an instance deletion has failed, and the instance has no longer its
database for io.cozy.settings, the command to remove the deleting
flag(1) was failing:

	$ cozy-stack instances modify --deleting=false <domain>
	Failed to modify instance for domain <domain>
	Error: not_found: Database does not exist.